# Generated by Django 6.1.1 on 2026-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('artista', models.CharField(max_length=300)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('popularidad', models.PositiveSmallIntegerField()),
                ('duracion_ms', models.DurationField()),
                ('fecha_lanzamiento', models.CharField(blank=True, max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Canciones',
                'ordering': ['-popularidad'],
            },
        ),
    ]
