# Generated by Django 6.1.1 on 2026-09-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='duracion_ms',
            field=models.PositiveIntegerField(),
        ),
    ]
